id: IF40F009B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:57:17+00:00'
last_modified: '2022-06-15T18:03:47.129539+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21818
  title: ནག་རྩིས་རྡེལ་འགྲེམ་འབྲས་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EB44:
      image_group_id: I1KG21886
      title: Volume 1 of nag rtsis rdel 'grem 'bras bshad/
      total_pages: 200
      order: 1
      base_file: EB44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
